# Generated by Django 2.0.7 on 2018-07-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gamers',
            new_name='Gamer',
        ),
    ]
